name: Code Coverage

on: ["push"]

jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
    - name: codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@0.1.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
