name: Dev CI

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Test
      run: npm run test:coverage

    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
